### ISSUE TITLE
Crashes if all prices are in the negative

### ISSUE THREAD

**Issue by cjeholm** [cjeholm/telldus_price_control#5]
If all prices fetched are below zero, the program crashes when drawing the graph.

**Comment by cjeholm** [comment]
Can not replicate the crash. Maybe tkinter version?

**Comment by cjeholm** [comment]
Found the error, a division by zero on line 621 that occurs when all of today's prices are negative and no price list yet exists for tomorrow, the script crashes at midnight.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/home/conny/Documents/telldus_price_control/./price_control.py", line 465, in timer_loop
    self.ratioprice()   # Run this to update ratio in case of date change
    ^^^^^^^^^^^^^^^^^
  File "/home/conny/Documents/telldus_price_control/./price_control.py", line 356, in ratioprice
    self.update_list_today()
  File "/home/conny/Documents/telldus_price_control/./price_control.py", line 621, in update_list_today
    self.graphheight / self.highestprice * max_height)
    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

```

**Comment by cjeholm** [comment]
Fixed and updated repo. Division by zero occurs when the lists highest price is equal to zero.
